### ISSUE TITLE
Rocket Sent Score hanging on the right side of YARM Status.

### ISSUE THREAD

**Issue by KaneHart** [narc0tiq/YARM#1]
Not sure if there is much you can do here but it's quite the eye sore. I know your considering adding rocket score to evoGUI But it's still an eyesore for people who might just use YARM Only.

http://i.imgur.com/Exs3iOe.png

Thanks.

**Comment by narc0tiq** [comment]
It's not my GUI, and moving YARM to `player.gui.top` would be even worse. Nothing I can do here, this is not a YARM issue.
