### ISSUE TITLE
Error when expanding site

### ISSUE THREAD

**Issue by okradonkey** [narc0tiq/YARM#107]
Repro steps:
Add new ore or oil site as usual.
Click + (expand site) button next to new site in YARM GUI.
Error appears immediately (see image below).

Error does not occur when clicking + next to certain "older" sites in my save, which may have been added using YARM 0.8.6.

![Capture](https://user-images.githubusercontent.com/48728363/56453109-580f6880-6302-11e9-85e4-70647b8af524.PNG)

**Comment by narc0tiq** [comment]
Looks to me like it shouldn't work with any sites at all -- I found what I messed up. Fix incoming.
