### ISSUE TITLE
crash on remote call when adding YARM to save

### ISSUE THREAD

**Issue by Choumiko** [narc0tiq/YARM#109]
```
  12.949 Error AppManagerStates.cpp:1398: The mod Auto Trash caused a non-recoverable error.
Please report this error to the mod author.

Error while running event AutoTrash::on_configuration_changed
Error when running interface function YARM.set_filter: __YARM__/resmon.lua:822: attempt to index field 'YARM_root' (a nil value)
stack traceback:
	__YARM__/resmon.lua:822: in function 'update_ui_filter_buttons'
	__YARM__/remote.lua:35: in function <__YARM__/remote.lua:27>
stack traceback:
	__AutoTrash__/control.lua:444: in function <__AutoTrash__/control.lua:337>
stack traceback:
	[C]: in function 'call'
	__AutoTrash__/control.lua:444: in function <__AutoTrash__/control.lua:337>
```

I'm currently rewriting AutoTrash. When trying to update my stored active_filter for YARM during on_configuration_changed i get the error.
It's a bit of a special case, since that save has an old version of AutoTrash and YARM isn't active in it, so due to load order i get to do the remote call before you had a chance to init your UI

**Comment by narc0tiq** [comment]
Fair enough; I could add a simple `if not [YARM_root] then return end`. Give me a few minutes, I'll make a dev build and you can try it out.

**Comment by narc0tiq** [comment]
Here we go, try [YARM-dev_0.8.13.zip](https://github.com/narc0tiq/YARM/files/3144356/YARM-dev_0.8.13.zip) and see if it fixes the problem.

**Comment by Choumiko** [comment]
Yeah that works. But turns out i really want a get_filter() remote, returning the players state or a default value (i think YARM defaults to warnings when adding the first resource site?). Right now i'm setting it directly to "warnings" in my global.
Not sure a lot of players are using AutoTrash and YARM at the same time, all uploaded versions still use the old remote call and i never got a complaint (Thanks btw for not just removing it :D )

**Comment by narc0tiq** [comment]
Gotcha, I'll add a `get_current_filter` call that doesn't update the value, plus the above fix, and those will go in the next release. Cheers!
