### ISSUE TITLE
idea: ore icon in list?

### ISSUE THREAD

**Issue by wchristian** [narc0tiq/YARM#114]
Pymods has a ton of ores and also different types of deposites for the same ore types, would it be possible to add an ore icon to the list?

Related to #4.

**Comment by narc0tiq** [comment]
I could almost trivially put the ore icon (technically the _first mining product_) right in with the ore name:
![image](https://user-images.githubusercontent.com/591573/57757495-456c3180-76fe-11e9-8cb6-fbc26425e440.png)

Look for it in the next version, I guess -- it looks fairly nice.

**Comment by wchristian** [comment]
That looks excellent. :D

**Comment by narc0tiq** [comment]
It turned out to be fairly easy to make it work with multi-product ores, too:
![image](https://user-images.githubusercontent.com/591573/57759481-aeee3f00-7702-11e9-94fa-497a03a8f1d5.png)

Look for it in the next release.

**Comment by wchristian** [comment]
That is a massive improvement. Thank you. :)
