### ISSUE TITLE
Estimated depletion time update

### ISSUE THREAD

**Issue by xystemat1c** [narc0tiq/YARM#118]
I configured the mod to update the estimated depletion time and available resources left every 120 ticks. But if the resource mining decreases, the values seem to not update properly. For example, I mine approximately 1200 iron ore per minute and the iron patch have xx hours left till depletion. Now I cut the miners from power. The shown values go slowly down to -700/m and stay there instead of decreasing to zero, while the estimated depletion time increases correctly and stays to the values calculated for -700 ore/m.

**Comment by jinks** [comment]
I noticed the same thing...

YARM appears to calculate ETD and usage over the whole lifetime of the ore patch. This is useful if you have a steady mining operation slowly belting all the ore into your base. Not so useful if you mine in bursts with large pauses in between.

I have a bunch of mining outposts that fill a train station at ~3k ore per minute and then stop until there's more room again. The usage numbers are more or less useless for me.

**Comment by narc0tiq** [comment]
Perhaps @wchristian could weigh in? Per #113, I was under the impression that we'd get a smoothed easing toward the current _actual_ mining rate -- that being 0/m -- not that it would freeze at some unexpected value. That said, maybe there's a bug in the calculation, perhaps related to changing the update rate?

I've been busy with my new child this past month, so haven't had a chance to contribute much, but as time allows I'll be back and will poke at this some more.

**Comment by AndrewSav** [comment]
I also noticed ETDs to be wildly inaccurate

**Comment by wchristian** [comment]
I can try and repro this. A save game would help too. :)

**Comment by wchristian** [comment]
#148 has a fix for this issue.

**Comment by AndrewSav** [comment]
@wchristian thanks, how many minutes it smoothes over? E.g. If I stop the production completely, when the rate reaches zero, and ETD reaches 'never'?

**Comment by wchristian** [comment]
@AndrewSav it doesn't actually do anything like "account for x minutes". What it does is "only apply 10% of the divergence between last and current value". However yeah, that ends up just never converging, so in this PR i changed the code to forcibly converge when the divergence is too small.
