### ISSUE TITLE
serious lack of information that yarm is now in the toolbar

### ISSUE THREAD

**Issue by kingarthur91** [narc0tiq/YARM#120]
so got a report the other day that yarm wasnt working with pymods and after trying to debug it i finally stumbled onto the fact that its buried in the little menu on the toolbar. maybe a note somewhere in the readme or mod portal that the tech and item no long exist would be helpful since i assumed it was still the same as it had always been and couldnt find anything saying otherwise

**Comment by narc0tiq** [comment]
Uh... I mean, I updated the readme when I made 0.8.0 in the first place: https://github.com/narc0tiq/YARM/commit/fb63655b44becbfe4d7ded346bbe6cae4d9123e2.
By request, I also copy-pasted the relevant bits to the description on the mod portal.
I've also noted the changes in the changelog (and also backfilled the changelog for the 0.7.x and 0.6.x series, as much as I could).

Do you have any thoughts where else I could publish the info?

**Comment by kingarthur91** [comment]
now that i know its there i do see its buried in the changelog but maybe a line noting the shortcut key in the info front page on how to use it
