### ISSUE TITLE
Marker stuck on map

### ISSUE THREAD

**Issue by Fyren** [narc0tiq/YARM#122]
I ended up with a map marker left behind by YARM even after turning off the map markers in settings (and waiting).  Here's screenshots with [markers on](http://sheap.net/~fyren/yarm_1.png) and with [markers off](http://sheap.net/~fyren/yarm_2.png).  I _was_ able to manually delete the extra marker, however.

I think the cause might be that I manually named two sites the same thing ("base") early on, though I haven't tried to reproduce it.  You can see I have eight sites in the list in the top left, but there are nine markers.

This is may be related to/a dupe of #52 if it was because of the name, but it was manual and not the autogenerated name clashing.

**Comment by narc0tiq** [comment]
I can confirm, this has the same cause as #52 (overwriting a site by renaming is just the same as overwriting by auto-naming) and the fix will be the same for both.
