### ISSUE TITLE
Yarn unredable on light backgtround. Add button to turn background black?

### ISSUE THREAD

**Issue by NetTecture** [narc0tiq/YARM#123]
As I say. On light for "multi color" background the text is very hard to rea.

Left you have filters. Add a button to the end that swtiches the background from "transparent" to "black", allowing the user to get a super readable version fast (and turn it back to transparent fast).

**Comment by Protheus** [comment]
![image](https://user-images.githubusercontent.com/1455178/84072508-9026ae80-a9cf-11ea-872c-7b7cdcaea0bf.png)
having a dark background would help as now I  can't read what the 2nd line is saying or what is displayed on the 1st

**Comment by jjcf89** [comment]
I wonder if the font settings let you set a black outline, sometimes that's all it takes to keep text readable.

**Comment by wchristian** [comment]
i've created a sketch of this here: #150

![image](https://github.com/narc0tiq/YARM/assets/175467/eb3dc0f2-66ad-4960-8394-1ddb97450323)

**Comment by narc0tiq** [comment]
Fixed by 63d63cb and further improved by #173
