### ISSUE TITLE
AAI Compatibility - Circuit Network Ore Signals

### ISSUE THREAD

**Issue by haineb** [narc0tiq/YARM#124]
I'm running a stripped down AAI deployment with YARM and am seeing some issues on circuit network signals. It looks like including YARM makes it so there are multiple signals for ore types.

Where this becomes an issue in AAI is that AAI uses tile scanners to generate signals for ore nodes to be mined on a tile. Tile scanner generated signals are "different" from the signals available in the regular circuit network logic post YARM install.

No idea if this lies directly in YARM or in AAI, but YARM lists AAI compatibility, so I figured I'd report here.

The attached save should show the issue:
[circuit-bug-test.zip](https://github.com/narc0tiq/YARM/files/4694537/circuit-bug-test.zip)
Check the signal inputs on the right combinator and you'll see a duplication, rather than addition.

Is this expected necessary behavior for YARM or is it a bug?

**Comment by narc0tiq** [comment]
Hi, sorry, I'm not actively maintaining YARM at the moment. I'll leave this link here to unify the discussions: https://mods.factorio.com/mod/YARM/discussion/5d1aae6c56d0c1000d9325cd
