### ISSUE TITLE
(Suggestion) on pressing "Enter" 

### ISSUE THREAD

**Issue by SGZ-Creations** [narc0tiq/YARM#146]
Can u please implement a way of using key binds to Exit/Confirm renaming. thinking of using "Enter" would be the correct one. 

![image](https://user-images.githubusercontent.com/59801736/161618805-48b46fc4-61d6-4830-982f-aa4e1d43e56a.png)

**Comment by narc0tiq** [comment]
Yes, agreed. It's already on my list at #75, but I really haven't had a chance to look into it yet. I do know other mods have this, so I just need to do the same thing... as soon as I figure out what the trick is.

**Comment by SGZ-Creations** [comment]
thanks for letting me know I'm just learning modding myself too.
