### ISSUE TITLE
Shown ETD is significantly off from actual time left

### ISSUE THREAD

**Issue by Zer0Key** [narc0tiq/YARM#156]
The shown ETD is significantly off from the actual time left, often on the order of days.
Same goes for consumption rate/m.
Just as an example:
An ore filed with two miners has 29k resource left, the displayed consumption is 490.3/m and ETD is 59 minutes. At my productivity lvl (3530%) that comes out to ~1M resource left and a consumption rate of 2178/m. The remaining time obviously doesn't change. If my math is correct that comes out to ~7h49m.
Something, somewhere is wrong when calculating ETD.
I looked at the code but I don't know enough about LUA and Factorio modding to figure it out my self.

**Comment by wchristian** [comment]
please upload your save file so i can look at it :)

**Comment by Zer0Key** [comment]
> please upload your save file so i can look at it :)

[Here ](https://www.mediafire.com/file/8attu6rxjq9t8q1/neu.zip/file)you go ;)

**Comment by Zer0Key** [comment]
You're welcome.
No worries on the time, this isn't your job (I presume).

> but the timings should be correct
Just so I don't misunderstand you. When you say the timings should be correct, do you mean currently, or after the bug fix?

**Comment by wchristian** [comment]
my job is other sorts of programming :)

and the times should be correct currently. if you disable the productivity adjustment in the options you should see that material, speed and etd match

**Comment by wchristian** [comment]
try with the most recent update. i also reworked how oil is displayed

**Comment by Zer0Key** [comment]
Not quite sure with the new calculation. Am I approaching this the wrong way, or?
Calculated values are for raw mining speed of 0.5/m per miner and adjusted for 3560% productivity.
I'd understand some discrepancy due to smoothing and getting the value from the difference between prior scan and current value but er, that's off by ~1.84x.

Also, if my math on time calculation isn't complete crap:
At 150/m and a deposit of 39,640 that'd take 264.26 minutes which works out to 4h24m.
Using the values from YARM (276.2/m works out to 143.52 minutes which is about 2h23m) the calculation for ETD seems correct just that the rate it uses seems to be off by ~1.84x.

I do like the new way of displaying oil.

![Screenshot 2023-08-07 125202](https://github.com/narc0tiq/YARM/assets/114016495/afa62bb3-c6ba-46f5-b619-a03330ec8b62)
![Screenshot 2023-08-07 125121](https://github.com/narc0tiq/YARM/assets/114016495/2db785cd-218e-417b-ac93-d36ac1fa87be)

**Comment by wchristian** [comment]
as a first intuition, i agree, it seems something is very wrong if the measured speed stones mined is bigger than what the miners can do

the first question would be whether the raw ore field depletion speed even matches the actual depletion, and the second one then if the multiplier of the efficiency research is interpreted correctly

i'll be testing, tho if you also would like to do some, that could help :)

**Comment by wchristian** [comment]
i'm thinking your UPS might also have something to do with it

**Comment by wchristian** [comment]
yeah, i get like 34 ups, and 60/34 is ~1.8, in the ballpark of your deviation, so imma have to think about how it measures time

**Comment by wchristian** [comment]
i added a setting so you can configure yarm with an average fps value which will be used to adjust mining speeds and ETDs. it won't be accurate since the UPS fluctuates, but better than nothing

measuring the actual game speed is possible, but very tricky and in danger of desync

**Comment by Zer0Key** [comment]
I'm currently still testing in the editor but so far I'm having a hard time reproducing the issue. Setting the game speed to 2x doesn't affect the rate and setting it to 0.5x doesn't either. Having a higher productivity research doesn't seem to affect it either. Once this current run of testing is through I'll run a test where I increase the productivity research in certain time intervals to see if maybe changing that has any effect. After that I'll run a test where the UPS change in intervals but I haven't figured out how to do that yet.

On the topic of time:
Isn't there an internal counter on how long a save has been played? Is that measured in real/system time or in game time? If it's measured in game time you could use that. If it's measured in real/system time I agree, it could get messy.

**Comment by wchristian** [comment]
it's a matter of perspective: you are thinking the game and thus the mod measures wallclock time. in reality both only work in ticks and *presume* 60 ups to convert ticks to wallclock time. which is why regardless of ups you saw the same exact rates :)

**Comment by Zer0Key** [comment]
I knew about measurement in ticks but I was looking at it in reverse. Now it makes sense.

I will test the new version tomorrow.

**Comment by Zer0Key** [comment]
Setting the nominal UPS is a bit finicky but getting the rate from rate calculator I can then adjust the UPS in the mod settings to get the rate as close as possible to the expected rate.
Interestingly, getting the rate correct for one resource patch doesn't mean all the others are correct. Quite far from it.
In the screenshot, the UPS are adjusted to match the stone patch, throwing all other patches completely off.
Still, it works.

![Screenshot 2023-08-08 202242](https://github.com/narc0tiq/YARM/assets/114016495/9415a501-fa2c-431b-9c66-99f898e45009)

**Comment by wchristian** [comment]
are you sure both of these patches are indeed being mined at full speed? i'd expect the deviation to stem from one of them, over a course of like 3 minutes, stopping occasionally

that said, yeah, the ups itself also changes over time and it is really tricky to measure it because multiplayer desynch needs to be avoided

**Comment by Zer0Key** [comment]
That makes sense.
Does the mod consider that the lower the remaining resource of a patch the slower it depletes?

**Comment by wchristian** [comment]
i haven't thought of a way to represent that algorithmically yet, so nope

**Comment by Zer0Key** [comment]
> i haven't thought of a way to represent that algorithmically yet, so nope

I've thought about this a bit. Here is what I came up with.
I originally wrote this in java and translated it to LUA with chatGPT so, there might be issues with this code. If it doesn't make sense, I can also post the java code.

```lua
-- CircularBuffer 
CircularBuffer = {}
CircularBuffer.__index = CircularBuffer

function CircularBuffer:new(capacity)
    local instance = {
        capacity = capacity,
        buffer = {},
        size = 0,
        head = 1,
        tail = 1
    }
    setmetatable(instance, self)
    return instance
end

function CircularBuffer:add(value)
    if self.size < self.capacity then
        self.buffer[self.tail] = value
        self.tail = self.tail + 1
        self.size = self.size + 1
    else
        self.buffer[self.head] = value
        self.head = (self.head + 1) % self.capacity
        self.tail = (self.tail + 1) % self.capacity
    end
end

function CircularBuffer:getBuffer()
    return self.buffer
end


-- Main code
-- Used to determine if trend is fast or slow
-- Defining variables, not sure if this is even necessary in LUA
minableResourceOld = 0 -- Previous snapshot of resource
minableResourceNew = 0 -- Current snapshot of resource
time = 60 -- Arbitrary time value, replace with actual time value
rate = 0.1 -- Rate of depletion
trend = 0.1 -- Depletion trend value
isTrendFast = false -- bool switch to change displayed rates and ETD

-- Calculate rate of depletion based on previous and current snapshot
function calculateRate(minableResourceOld, minableResourceNew, time)
    rate = (minableResourceNew - minableResourceOld) / time
    return rate
end

-- Calculate trend based on rate and current snapshot
function calculateTrend(rate)
    trend = rate / minableResourceNew
    return trend
end

-- Determine if trend is fast or slow
-- replace upper and lower bounds with values that make sense
-- Which values make sense? Idk, use experience to guess.
function isFast(trend)
    local lowerBound = -10.1
    local upperBound = 10.1
    if trend >= lowerBound and trend <= upperBound then
        return false
    end
    return true
end

-- Does the same as isFast but with smoothed values using CircularBuffer
function isFastBuffer(buffer)
    local lowerBound = -10.1
    local upperBound = 10.1
    local sum = 0
    for i = 1, #buffer do
        sum = sum + buffer[i]
    end
    local average = sum / #buffer
    if average >= lowerBound and average <= upperBound then
        return false
    end
    return true
end

-- Creating an instance of CircularBuffer
bufferSize = 5 -- Not actual buffer size, replace with actual value
circularBuffer = CircularBuffer:new(bufferSize)

valuesToAdd = {1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0} -- Not actual values to be added, replace with (probably) stream from mod

for i = 1, #valuesToAdd do
    circularBuffer:add(valuesToAdd[i])
end

bufferContents = circularBuffer:getBuffer()
for i = 1, #bufferContents do
    print(bufferContents[i])
end

```

**Comment by Zer0Key** [comment]
Deleted my previous post as I found multiple mistakes in my logic. I wrote that at 3am. Will come back with a better idea and working logic.

**Comment by wchristian** [comment]
Thanks for our efforts and no worries. I've been a bit silent as i was travelling. Looking at your code, the main part is setting up a circular buffer, which YARM already sidesteps by having a bit of code on each update that takes the delta of previous resource remaining and currently measured, multplies that by 0.1 and then subtracts that delta from the previous to get a smoothed current value.

The primary issue would be what exact math to do when yarm detects that the entity count within a site changed.

**Comment by Zer0Key** [comment]
I've come up with the math but haven't fully put it into code yet.

```
What is needed for this to work:
A snapshot of the resource (R) and a timestamp when that snapshot was taken. (For the timestamp use either mod internal clock or online_time from Factorio.)
Get the rate: R(current) - R(old) / time difference
Next, you get a data point by first doing (R(current) + R(old)) / 2 and then rate / R(average) (The average is for avoiding division by very small numbers.)
Now calculate the standard deviation of the data points:
First, get the average of all data points (D average): Sum(datapoints) / Number(datapoints).
Then, for each data point, get the squared difference: (datapoint - D average) * ( datapoint - D average) or in other terms: (datapoint - D average)²
Then, get the average of all squared differences(AvgSqrdDiff): Sum(sqrdDiff) / Number(sqrdDiff)
Now, get the standard deviation(StdDev): Square Root of AvgSqrdDiff
Next, calculate the thresholds: 
threshold_low = D average - StdDev
threshold_high = D average + StdDev
Lastly, determine how quickly the trend is changing: 
D average > threshold_high = quick increase
D average < threshold_low = quick decrease
Otherwise consistent trend.
``` 
This way there is no need to set your own cutoff points for high or low rate of change because it is determined mathematically.

For storing the time stamps and the resource count snapshots I'm using Map<Integer, int[]> as a HashMap in Java. Where the Integer is the Key and the int[] are the time and resource count. That way it is possible to store both at the same time and retrieve them in pairs to then perform math on them without running into sync issues.

Here is what I've written so far but it's not yet finished and I haven't tested or even looked over this again. There might be (embarrassing) mistakes in this.

Class that handles all the resource patch data. Wrote this to make my own code internally consistent, even if the mod already has something like this. This is finished but untested.
```java
import java.util.HashMap;
import java.util.Map;
/* This stores pairs of snapshots of a given resource patch.
 * It takes in the timestamp of the snapshot as well as the resource count.
 * Timestamps and resource counts need to be passed to an object of this from elsewhere.
 * The key needs to be unique and assigned when passing data to the object, otherwise data will be overwritten.
 * Deleting a snaphot is possible by passing its key to the object.
 */
public class Snapshots {
    private Map<Integer, int[]> storageMap;

    public Snapshots() {
        storageMap = new HashMap<>();
    }

    public void addSnapshot(int key, int timeStamp, int resourceCount) {
        storageMap.put(key, new int[]{timeStamp, resourceCount});
    }

    public void removeSnapshot(int key) {
        storageMap.remove(key);
    }

    public int getTimeStamp(int key) {
        int[] pair = storageMap.get(key);
        if (pair != null) {
            return pair[0];
        } else {
            throw new IllegalArgumentException("Key not found: " + key);
        }
    }

    public int getResourceCount(int key) {
        int[] pair = storageMap.get(key);
        if (pair != null) {
            return pair[1];
        } else {
            throw new IllegalArgumentException("Key not found: " + key);
        }
    }
}

``` 

Class that handles all the calculation. Mostly finished, needs standard deviation calc and some other bits and bobs. Has mistakes in it that break it.
```java
import java.util.ArrayList;
import java.util.List;

public class EvaluateTrend {
/* This calculates the rate of depletion of a given resource patch,
 * gets a trend based on the depletion rate,
 * and then makes a qualitative statement about how quickly the trend is changeing,
 * determined dynamically based on the trends data.
 * The returned statements are: quick increase, quick decrease, consitent and insufficient data.
 */

    private List<Double> trendData = new ArrayList<>();
    private double dataPointTrend;
    private double averageTrendData;
    private double stdDeviationTrendData;
    private int snapshotCount;
    private int timeDifference;
    private int resourceDifference;
    private double rate;
    private double averageResource;
    private Snapshots resourcePatch = new Snapshots();

    

    public int calcualteTimeDifference() {
        timeDifference = resourcePatch.getTimeStamp(snapshotCount) - resourcePatch.getTimeStamp(snapshotCount-1);
        return timeDifference;
    }

    public int calculateResourceDifference() {
        resourceDifference = resourcePatch.getResourceCount(snapshotCount) - resourcePatch.getResourceCount(snapshotCount - 1);
        return resourceDifference;
    }

    public double calculateRate() {
        rate = resourceDifference / timeDifference;
        return rate;
    }

    public double calculateAverageResource() {
        averageResource = (resourcePatch.getResourceCount(snapshotCount) + resourcePatch.getResourceCount(snapshotCount - 1)) / 2;
        return averageResource;
    }

    public double calculateDataPointTrend() {
        dataPointTrend = rate / averageResource;
        return dataPointTrend;
    }

    public void appendTrendData() {
        trendData.add(dataPointTrend);
    }

    public double calculateAverageTrendData() { // FIXME needs average calculation
        averageTrendData = 0;
        for (double trendData : trendData) {
            averageTrendData += trendData;
        }
        return averageTrendData;
    }

    public double calculateStdDev() {

    }
}

```

**Comment by Zer0Key** [comment]
I totally forgot I was working on this at one point.
Yes, calculating productivity is not necessary to get the ETD. It's a nice to have data point to show but won't change anything in regards to depletion time. Which is why I omitted it in my thrown together code (that is written in the wrong language because I still haven't learned LUA).
The source of the issue still remains UPS, everything else around it is extra features. The fix of allowing the user to change the nominal UPS works but is a bit clunky. My thought was to get the game time to calculate depletion rate, since game time is the same as UPS. Throwing in the standard deviation and trend is just to get more nice data to show. That code, as much as it is in the wrong language, is pretty much done in terms of core features and concept. I just got busy with Uni and forgot about it. I don't really have the skills to turn this into a pull request but feel free to use the concept for inspiration.

**Comment by wchristian** [comment]
As far as i got last time with my research is that the scripts have no way to access the realtime clock, so all values are always in UPS-scaled time.

**Comment by Zer0Key** [comment]
Essentially the issue is "fixed" with a clunky solution.
The source of the issue was that I assumed that the displayed ETD was real-time and not game-time irrespective of UPS. Since then we have been discussing other ways to fix this and, admittedly, OT features.
So, I'd agree. Close this as fixed and move it to discussions.

**Comment by narc0tiq** [comment]
Discussion ready at #182
