### ISSUE TITLE
YARM 0.10.8 crash at save loading

### ISSUE THREAD

**Issue by SoulsD** [narc0tiq/YARM#160]
> The mod YARM - Resource Monitor (0.10.8) caused a non-recoverable error.
Please report this error to the mod author.
>
> Error while running event YARM::on_configuration_changed
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	[C]: in function '__index'
	__YARM__/resmon.lua:80: in function 'init_player'
	__YARM__/resmon.lua:32: in function <__YARM__/resmon.lua:30>

Previous YARM version linked to save is 0.8.210

**Comment by JonScarlet** [comment]
I believe I made an inquiry into that earlier today, and it should already be fixed if you haven't updated it yet.

**Comment by wchristian** [comment]
i may have misunderstood something the code was doing, new release with a better fix is out

also she/they please :)
