### ISSUE TITLE
Marker stays after depletion

### ISSUE THREAD

**Issue by XenoxUSser** [narc0tiq/YARM#162]
I marked iron the marker says that its finished now and stayed there since 2 days deleting doesent work it creates it again and yeah the marker just exist being red and showing "now"

![image](https://github.com/narc0tiq/YARM/assets/33065711/5a239876-b6ed-4ac6-9fc9-c32e7993faa4)

![image](https://github.com/narc0tiq/YARM/assets/33065711/d513b2df-9d82-4ff5-b6e1-dcff47fd86a4)

Edit: i checked every corner if theres maybe some ore left or anyhting turning off markers makes the marker on map dissapear but still shows the site top left

**Comment by wchristian** [comment]
does it go away when you delete the site entry in the interface, rather than the map tag?

**Comment by narc0tiq** [comment]
NB: YARM doesn't think there's anything special about a site with 0 ore in it (maybe you want to remember where it was?) so it won't delete the site automatically for you. This is not a bug.
