### ISSUE TITLE
Scanned info is replaced by other

### ISSUE THREAD

**Issue by sakuro** [narc0tiq/YARM#164]
When I scanned a copper, coal then iron patch, copper patch line was replaced with newly scanned iron patch.

Factorio version: 1.1.92 / Windows 11
Playing with Krastorio 2, Very BZ and some QoL mods.

[Save(Sep 27.zip)](https://github.com/narc0tiq/YARM/files/12738481/Sep.27.zip)
[Video(imgur)](https://imgur.com/a/HPBjh47)

Is this a duplicate of https://github.com/narc0tiq/YARM/issues/52 and https://github.com/narc0tiq/YARM/issues/68 ?

**Comment by wchristian** [comment]
Yep, that's exactly the same issue as #52. You can workaround it for now by renaming the first site, but i'll have to implement a fix here. Thanks for bringing it to my attention. :)

**Comment by sakuro** [comment]
Renaming works! thanks.
