### ISSUE TITLE
Resource overlay remained "on" and then factorio crash

### ISSUE THREAD

**Issue by annekaelber** [narc0tiq/YARM#167]
> The mod YARM - Resource Monitor (0.10.14) caused a non-recoverable error.
> Please report this error to the mod author.
> 
> Error while running event YARM::on_tick (ID 0)
> LuaEntity API call when LuaEntity was invalid.
> stack traceback:
> 	[C]: in function '__index'
> 	__YARM__/resmon.lua:453: in function 'scan_current_site'
> 	__YARM__/resmon.lua:1676: in function 'update_players'
> 	__YARM__/resmon.lua:1733: in function 'on_tick_internal'
> 	__YARM__/resmon.lua:1767: in function <__YARM__/resmon.lua:1762>

I am using the dangOreous mod. Normally, on the occasion when I slip and 'select' some minerals, it'll grow that site. until it seems to be satisfied. This time, I was walking back to my base when the crash happened. I'll be glad to provide more details.

**Comment by narc0tiq** [comment]
Probably fixed by #180

**Comment by narc0tiq** [comment]
Also, with dangOreus, please make sure you have configured a maximum site size in the mod settings; the default is -1, meaning infinite, and while I'm pretty sure YARM won't generate more ore patch, it will also likely not generate useful sites either. Also check #111 for a future feature to limit a site to exactly selected entities.
