### ISSUE TITLE
subsurface 1.0.5 and YARM_0.10.14 incompatible

### ISSUE THREAD

**Issue by angrypidgeon123** [narc0tiq/YARM#168]
https://github.com/NathaU/factorio-subsurface/issues/8

---

Hacked a solution for myself in subsurface mod (and since subsurface 1.0.3 not incompatible, problem solved :D):
https://github.com/NathaU/factorio-subsurface/issues/10

---

Hack failed, probably because yet another mod, still working at it.

Until then attacked the problem at this mod, added a check in data-final-fixes.lua

require "resmon"

local ore_items = {}

for name, proto in pairs(data.raw.resource) do
	if string.starts_with(proto.name, "subsurface-hole") then break end

**Comment by narc0tiq** [comment]
Fixed in the other mod, but also mitigated by #178
