### ISSUE TITLE
Error with displaying using graftorio 2

### ISSUE THREAD

**Issue by protocol-1903** [narc0tiq/YARM#171]
Hi there,
I'm using [graftorio 2](https://mods.factorio.com/mod/graftorio2) to view production, consumption, etc outside of the factorio client. It has listed mod support. For whatever reason, not every patch is being listed and sent to the server. It's inconsistent with where it does and does not pick up a listed ore patch. My guess is something to do with not calling a specific function somewhere or another... Can you check if all remote interface calls are correct? I'm going to check the other mod to see if everything is working there. Thank you!

**Comment by narc0tiq** [comment]
Without any further ideas of what might be causing the issue, I will now close this story. If you get more information, please reopen.
