### ISSUE TITLE
 Error Autosave / Save

### ISSUE THREAD

**Issue by Storm-Reaver** [narc0tiq/YARM#172]
Map cannot be saved: The mod YARM - Resource Monitor (0.11.0) caused an error that cannot be fixed.
Please inform the author of the mod about this error.

Error while running event YARM::on_save()
Cannot serialise lua functions

The error always occurs during autosave, normal saving and loading works but no autosave is created 

ridesdragons:
for me it's the other way around - autosaves seem to be functioning, but I can't manually save

**Comment by fkarg** [comment]
Well, it's on autosave for us (server, hosted by me). Manual saving works fine.

```
The mod YARM - Resource Monitor (0.11.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event YARM::on_save()
Cannot serialise lua functions
```

**Comment by Gerkiz** [comment]
The iterator is saved to the storage table, which is not ideal: `storage.ore_tracker.iterator_func` 👎

**Comment by wchristian** [comment]
> The iterator is saved to the storage table, which is not ideal: `storage.ore_tracker.iterator_func` 👎
> 
> Located here:
> 
> https://github.com/narc0tiq/YARM/blob/4eda629eb250bc3a807bdfbfebdda34b164c1d6a/libs/ore_tracker.lua#L152

What's a better place to store it?

**Comment by narc0tiq** [comment]
No, no, we shouldn't save it, that's the problem -- we need to get a new one each time. The iterator state and key have to be enough to resume iteration. Factorio 1.1 was silently ignoring our request to save the iterator anyway, so we've been unexpectedly doing this all along for the last 3 years anyway, but now we should do it on purpose.

I'll take a look at how a patch for that might look like, I can still mostly remember how the ore tracker works.

**Comment by wchristian** [comment]
Having some real trouble trying to figure this one out, particularly since i can't reproduce it. Are any of y'all able to have this happen reliably? A savegame of that would be great, as well as some context info of which mods you're using and whether you're using a fresh 2.0 save.

**Comment by wchristian** [comment]
We got a savegame in [this thread](https://mods.factorio.com/mod/YARM/discussion/6717ddcf7f2ed0bc3fa5692f), and in replying to it i also realized it would be useful if any people affected could share their factorio-current.log

**Comment by wchristian** [comment]
Talked to a factorio dev, and they confirmed that the storage is exclusive to YARM, so it is something in our code.

**Comment by narc0tiq** [comment]
Ok, good news, I have reproduction steps: you have to be in the middle of adding a site (either scanning for resources or just waiting for the scan to time out). If it just sits there, nothing will go wrong, but if you (or anyone else, in multiplayer!) happen to be adding a site then the state of the game during this step includes some function somewhere in YARM's storage.

**Comment by narc0tiq** [comment]
Ok, revising my previous statement: if it just sits there _with relatively few and small sites_, nothing will _likely_ go wrong -- I've found the likely culprit:

https://github.com/narc0tiq/YARM/blob/4eda629eb250bc3a807bdfbfebdda34b164c1d6a/resmon.lua#L669

Locally it looks fine, right? `site.iter_fn`, we're just putting something into this local... but actually, its true name is `storage.player_data[game.get_current_player()].current_site.iter_fn` and that's much more obviously not ok because we're trying to put a *function* into *storage*.

There are two cases where we enter here, once is when finalizing a site (after creation or expansion _with addition of entities), the other is when updating site totals for each force, which happens rarely enough you wouldn't run into it unless you were _really_ lucky. Happily, finding the first case let me find both.

**Comment by 1n5aN1aC** [comment]
I don't honestly think factorio logs would be useful, but I just experienced the crash, and someone asked for them above, so here ya go:

```14296.785 Info AppManager.cpp:290: Saving to _autosave6 (non-blocking).
14296.800 Info AsyncScenarioSaver.cpp:162: Saving process PID: 909
14297.151 Info ChildProcessAgent.cpp:61: Child 909 exited with return value 0
14297.151 Info AppManager.cpp:291: Saving finished
14785.169 Info ServerMultiplayerManager.cpp:1083: Disconnect notification for peer (3)
14785.169 Info ServerMultiplayerManager.cpp:971: updateTick(4889304) received stateChanged peerID(3) oldState(InGame) newState(DisconnectScheduled)
14785.169 Info ServerSynchronizer.cpp:613: nextHeartbeatSequenceNumber(887010) removing peer(3).
15196.785 Info AppManager.cpp:290: Saving to _autosave7 (non-blocking).
15196.799 Info AsyncScenarioSaver.cpp:162: Saving process PID: 932
15197.145 Info ChildProcessAgent.cpp:61: Child 932 exited with return value 0
15197.145 Info AppManager.cpp:291: Saving finished
16096.785 Info AppManager.cpp:290: Saving to _autosave8 (non-blocking).
16096.796 Info AsyncScenarioSaver.cpp:162: Saving process PID: 955
16097.161 Info ChildProcessAgent.cpp:61: Child 955 exited with return value 0
16097.161 Info AppManager.cpp:291: Saving finished
16605.502 ConnectionRequestReplyConfirm (type(ConnectionRequestReplyConfirm) ) from(IP ADDR:({10.0.0.111:64335}))
16605.502 Info ServerRouter.cpp:465: Replying to connectionRequest for address(IP ADDR:({10.0.0.111:64335})).
16605.502 Info ServerSynchronizer.cpp:594: nextHeartbeatSequenceNumber(996229) adding peer(5)
16605.521 Info ServerMultiplayerManager.cpp:803: updateTick(4998525) changing state from(InGame) to(InGameSavingMap)
16605.552 Info ServerMultiplayerManager.cpp:971: updateTick(4998525) received stateChanged peerID(5) oldState(Ready) newState(ConnectedWaitingForMap)
16605.732 Warning WriteFileGuard.cpp:51: Writing /factorio/temp/mp-save-4.zip failed; previous version (if any) should still be available
16605.733 Error ParallelScenarioSaver.cpp:156: Saving scenario failed: The mod YARM - Resource Monitor (0.11.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event YARM::on_save()
Cannot serialise lua functions
16605.735 Error ServerMultiplayerManager.cpp:84: MultiplayerManager failed: save-map-failed.cannot-save-map("Cannot save map: The mod YARM - Resource Monitor (0.11.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event YARM::on_save()
Cannot serialise lua functions")
16605.735 Info ServerMultiplayerManager.cpp:803: updateTick(4998525) changing state from(InGameSavingMap) to(Failed)
16605.752 Quitting: multiplayer error.
16606.056 Info ServerMultiplayerManager.cpp:146: Quitting multiplayer connection.
16606.056 Info ServerMultiplayerManager.cpp:803: updateTick(18446744073709551615) changing state from(Failed) to(Closed)
16606.059 Info UDPSocket.cpp:233: Closing socket
16606.059 Info UDPSocket.cpp:263: Socket closed
16606.059 Info UDPSocket.cpp:233: Closing socket
16606.132 Info UDPSocket.cpp:233: Closing socket
16606.132 Info UDPSocket.cpp:263: Socket closed
16606.134 Goodbye
```

**Comment by wchristian** [comment]
A release with a fix is out. Please test it and reopen this if it still happens. :)

**Comment by 1n5aN1aC** [comment]
Appears to be working.  I couldn't trigger the crash at-will before, but I have not been able to trigger it recently, so I *THINK* it's fixed now.

Thanks much!!
