### ISSUE TITLE
Improvement: use LuaRendering instead of making an inoperable chest as an overlay marker

### ISSUE THREAD

**Issue by narc0tiq** [narc0tiq/YARM#175]
Currently, the overlays are done by placing a `rm_overlay` entity belonging to the `neutral` force and telling it to be unminable, inoperable, and indestructible. While this technically _works_, it's also placing a fairly high-cost item into the world when we really just wanted to draw some blue on top of the tiles we know about, so the player can know we know about them.

The control code that places the overlay entities is found here:
https://github.com/narc0tiq/YARM/blob/9eedf5c821ecf46fe36a5f28bbc962dbfd933910/resmon.lua#L408-L421

Since we now have [LuaRendering](https://lua-api.factorio.com/latest/classes/LuaRendering.html) for this purpose, which provides a convenient `draw_rectangle` (or even `draw_sprite` if someone is feeling creative!), why don't we just use that?

P.S.: Yes, I should have done this years ago.

**Comment by wchristian** [comment]
The link to luarendering isn't rendered correctly. :D

Also hmm, i was thinking draw_polygon, but that's only after skimming. Sounds like a very good change though. Don't know when i'll get around to it, since the past two days were hectic, but i would wanna do this soon, yes. :D
