### ISSUE TITLE
Still (or again?) can't view site on a different surface

### ISSUE THREAD

**Issue by narc0tiq** [narc0tiq/YARM#176]
Clicking the button to go to my Vulcanus coal mine showed me a view of Nauvis; we can actually supply a surface to `LuaPlayer.set_controller` and the site has a surface, so the simplest change would be here: https://github.com/narc0tiq/YARM/blob/9eedf5c821ecf46fe36a5f28bbc962dbfd933910/resmon.lua#L1477

**Comment by wchristian** [comment]
I'm not a 100% sure this is correct, but this should work, so i've committed it and will make a release now: https://github.com/narc0tiq/YARM/commit/6d15ebc6464c895d11055f97c7da58a2a591ee14 At the very least it doesn't crash. :D

Also i think it never worked before. :)

**Comment by wchristian** [comment]
Alright, release is out, can you test it?

**Comment by narc0tiq** [comment]
Yup, totally works
