### ISSUE TITLE
When launches a saved game

### ISSUE THREAD

**Issue by Toys0125** [narc0tiq/YARM#21]
When I launch in a saved game the progress goes down to zero  and i have to redo the selecting of the mining sites. I also have other mods that could affect it like Resource overhaul or rso. i goes down and says that 1320000m/s on the tacker so I don't know how to fix it

**Comment by narc0tiq** [comment]
Sorry, Factorio 0.12.13 and 0.12.14 both have this issue: <http://www.factorioforums.com/forum/viewtopic.php?f=7&t=17275>.

Not a YARM bug, I'm afraid.

**Comment by Toys0125** [comment]
thank you for helping me i will wait for the update
