### ISSUE TITLE
Localization aid: either a setting or a specific locale key for thousands and decimal separators

### ISSUE THREAD

**Issue by narc0tiq** [narc0tiq/YARM#22]
Because seemingly every language has its own way of doing it.

**Comment by mexmer** [comment]
string.format should format number in proper locale (unless you set different one using os.setlocale function - not sure, if that one is allowed in Factorio virtual machine tho' )

but depends what you want to achieve, if this is way for you, or not.
i prefer to stick with EN_US formating in most cases, if i'm writing universal code without localization awarenes.

**Comment by narc0tiq** [comment]
I'm dropping this issue, as I can't quite justify the code necessary to make it work.
