### ISSUE TITLE
Better handling for oil well-like resources.

### ISSUE THREAD

**Issue by narc0tiq** [narc0tiq/YARM#29]
As I noted on the forums at https://forums.factorio.com/viewtopic.php?f=92&t=16698&p=131932#p131932, oil wells, hot springs, and any other resource that might use similar behaviour are very tedious to set up for monitoring.

My only idea at the moment is to use a different mode for the monitor item (perhaps using a crafting recipe to convert it?) that would either increase the range of the new site scan or perform a box selection of some kind. 

Or it might just keep searching around the player (within a reasonable radius) during those 10 seconds before the site is created, letting you run around without having to actually click each well resource (as long as you run close enough to them). Possibly this latter could be used for regular resources as well: click a resource to set the target and then run around and let proximity determine what gets added to the site.

**Comment by Squeaker** [comment]
Could always just use a longer time-out when clicking those...

or... you click one, and then draw a selection box to include the others of the same type during the 10 (or 20) second window...

**Comment by narc0tiq** [comment]
"Draw a selection box" sounds interesting -- something like the deconstruction planner, yes? Can we do that and have it mark resources for us, or at least tell us the bounds (in map coordinates) of the selection so we can do the same? Note to self, find out how the upgrade planner works.

**Comment by dgw** [comment]
Very pleased to see that this is in the issue tracker already. I added YARM to my game today and have been running around adding current mining sites. Oil is the only one that's unbearably tedious, because I have to click every single well… 😆

**Comment by narc0tiq** [comment]
Fixed by v0.8 by using exactly the selection box method that was previously mentioned.
