### ISSUE TITLE
Some option(?) to auto-add radar-detected sites.

### ISSUE THREAD

**Issue by georgehank** [narc0tiq/YARM#37]
Still mulling this over, and still pondering how to add this to the code.  I think I see the code side.  I just haven't added it yet... since I'm still unsure how to balance this.  Probably a higher piece of research... hmm, don't know if a mod can add modules.  Also, I'd want this to be there early.  Dang, decisions, decisions... ;-)

**Comment by narc0tiq** [comment]
The problem I have with this is that the more entities you're tracking, the slower your game will run; it's really easy to drop below 60 UPS with YARM.

The other problem is interface: there's no pagination yet, so if you create many sites they're going to scroll off the bottom of your screen.

Finally, actually scanning for ores is going to take a bunch of processing time, possibly a noticeable freeze whenever you place a radar (doing it slower is better, but more difficult).

---

If you'd like to implement it, you're more than welcome; I'd agree that it seems like a blue-science level research, so some kind of upgrade to the regular resource monitor.

It will also **require** a settings interface, and probably some way to merge sites. Finally, you'd want to take a close look at the automatic naming scheme and try to avoid generating sites with the same name (automatic suffix would be acceptable), which is a rare but very unfortunate event that can happen currently.

**Comment by Thel89** [comment]
As an idea, I'd probably approach this with the mindset of "don't track them until the player asks to, but just be aware of where they are so we can easily add them" - so radar discovery would auto-add ore patches to a tagged list (which would ideally be filterable by distance, direction, size, ore type), and the player could then 'promote' patches from the tagged list to the active list. Again, though, it'd need some sort of management UI.

You'd have to be a bit careful how you wrote the auto-add code, though - if you have a tagged ore patch that spreads over both a discovered chunk and an undiscovered chunk, when the radar exposes the undiscovered chunk that'll change the tagged patches' extent (and then potentially the name, which is the index into the sites table).

**Comment by narc0tiq** [comment]
Yeah, it's non-trivial for sure, both interface-wise and code-wise. Performance probably isn't as much of a worry as it was before, though. Still have to wonder about what happens when you place a radar, but that's chunkable, too, I imagine.

**Comment by petergaultney** [comment]
This is probably no longer necessary (or at least much less necessary) as of 0.15, since the map will show the quantities of ore as soon as they're discovered.

**Comment by narc0tiq** [comment]
With the new miner support for reading an ore patch to the circuit network, plus the aforementioned map improvements, I'm thinking YARM itself can be reduced to a more generic "estimate time to depletion" tool that could work on anything circuit-publishable.

Regardless, automatically creating sites is something I was never keen on, and I much prefer that the base game has rendered it moot.
