### ISSUE TITLE
Remote viewer attacked by biters

### ISSUE THREAD

**Issue by narc0tiq** [narc0tiq/YARM#38]
Via <https://forums.factorio.com/viewtopic.php?p=169934#p169934>:
> I have a iron patch near a biter nest scanned with yarm, when i went to take a look at it, i died to the biters. Dont think this was intented to happen.

**Comment by Nexela** [comment]
This is an easy fix, in prototypes.lua:127
change: fake_player.healing_per_tick = 100
to: fake_player.max_health=0
Entities with 0 health can't be attacked.

**Comment by narc0tiq** [comment]
Thank you, I've added that in ca7adf4372519daf5277b30dfbe02b7023dbf455.
