### ISSUE TITLE
Colorize ore name by map color

### ISSUE THREAD

**Issue by narc0tiq** [narc0tiq/YARM#4]
Via http://www.factorioforums.com/forum/viewtopic.php?p=111068#p111068: apply the ore's map color just to the ore name in the listing.

Via http://www.factorioforums.com/forum/viewtopic.php?p=111177#p111177, we have this lovely mockup from Waduk:
![mockup](http://i.imgur.com/KIkQ8My.jpg)

That doesn't use the right ore map colours; it'll be interesting to see if the real colours look any good -- the example iron ore is a bit hard to read, and I suspect at least some of the real colours will be similarly bad (but we already have this problem with the red-yellow-green colouring, so this is not a reason to avoid doing it).

**Comment by wchristian** [comment]
Instead of colorizing the text it could just colorize a static square. (Optimally one with a black 1px boundary around it, then a white boundary around that, for better visibility on different backgrounds.)

**Comment by narc0tiq** [comment]
So I just poked at this, and it definitely needs some kind of background: 
![image](https://user-images.githubusercontent.com/591573/57756843-c9251e80-76fc-11e9-8335-701fb87d6487.png)

I don't know that it would make that much difference making it a square versus just coloring the text, but it's clear that there needs to be some aid to contrast.

**Comment by wchristian** [comment]
Having it be a square separate from the text would've allowed adding the color without impacting the color/readability of the text, but i think this is fairly obviated by #114.

**Comment by narc0tiq** [comment]
I'm strongly considering just closing this in favor of the ore icons.

**Comment by narc0tiq** [comment]
Resolved by ore icons
