### ISSUE TITLE
Warnings after quiting game when in yarm

### ISSUE THREAD

**Issue by mexmer** [narc0tiq/YARM#45]
Can't do better description, so just "situation" that lead to this.
I was playing MP with friend, and either due network error or w/e we both got disconnected. I was inside yarm that time.
When i reconnected i was at same place i was before (not in YARM), but since then, whenever i try to enter or exit YARM watch point i get what you see on image.

If i rollback server prior that disconnect, everything is fine.

![image](https://cloud.githubusercontent.com/assets/5429727/17642601/6a6b0ea4-614c-11e6-8575-f623d4caeb51.png)

**Comment by narc0tiq** [comment]
Okay, I'm glad to hear you're able to recover it by rolling back to the earlier save. I'll get this fixed for the next version of YARM, thanks for the report.

**Comment by mexmer** [comment]
thanks
