### ISSUE TITLE
Configurable auto-name template

### ISSUE THREAD

**Issue by narc0tiq** [narc0tiq/YARM#48]
Note: this is the enhancement counterpart to bug #52. My current thinking is to split the site internal names (used to reference the sites with `force_data`) from their display names, which also gives us the opportunity to involve the localization system for display names.

As a stretch goal for 1.0, this seems within the realm of possibility but will be a fairly large change (and migration) from the 0.x data structures.

---
Original description:

Correctly identified by **Anson** at https://forums.factorio.com/viewtopic.php?p=197305#p197305 -- the auto-naming should be configurable, most likely with simple printf-style %markers (or with {keyword} markers).

Relatedly, when a new site's name collides with an existing one, offer a dialog to rename the new one or (if possible) merge it into the existing one.

**Comment by dgw** [comment]
I guess this is related to #68, re: name collision handling.

**Comment by ChuckSavage** [comment]
I'm guessing this is low priority, since it was suggested 2 years ago, but I've some ideas for this as well.

If the printf() type thing gets implemented, some catagories to consider.

Total ore sites counter.
Individual ore site counter. IE, each ore type would have their own counter.
Ore name and ore abbreviations, such as "Copper", "Cpr", and "C" (Coal would have to use some other single letter)

**Comment by mrudat** [comment]
Now that we've got rich text, perhaps %ore-icon? not sure how well %ore-name would work given localisation?

**Comment by narc0tiq** [comment]
Ore name definitely wouldn't work, exactly because of localization. Site names aren't localized, and I don't want to bring the locale system into it, either. The ore icon is just a perfectly fine idea, though.

Please note that printf markers are traditionally **one character**, so it's either `%i %q %o %d` (short, but cryptic) or `{ore-icon} {quadrant} {distance-from-origin} {index-per-ore}` (long, but much more intelligible).

There would need to be some documentation, too, to specify that "quadrant" is an intentional misnomer for _octant_ (because "quadrant" is a more familiar term) and that "index-per-ore" refers to the per-ore-type counter previously described.

**Comment by narc0tiq** [comment]
As a stretch goal for 1.0, we can probably do something with this. Obviously, since 2019 things have changed a bit, and my current thinking is along the lines that I'd like to bring the locale system into it:
- There should be an internal name that would relatively uniquely identify the site (e.g., `"nauvis@134,512:iron-ore"`) that the player need never actually _see_, but which can find the site inside the YARM data structures.
- Completely separately, there should be a user-configurable, optional name for each site (like a tag perhaps) that I expect to remain unused most of the time; you could use this to specify that a site is feeding a gear factory, for example.
- And finally, a configurable display name made of components that can also pass through localization; this is where you would put things like `planet name`, `distance from origin`, `site center coordinates`, or `site number` and place them around the player-given name described above (either before or after, and in configurable order).

The player should not need to specify anything when creating a site, but may tag it at any point after the fact, and updating the display name configuration should update all sites equally. With configurable columns (#24), the site name may even potentially be omitted from the HUD display altogether, although that seems less useful.

**Comment by narc0tiq** [comment]
So I've started working on this for 1.0, it looks like we're going with `[square bracket tags]` as follows:
- `[planet]` will translate to the (localised!) planet name, e.g. "Nauvis" or "Gleba".
- `[4-way-compass]`, `[8-way-compass]`, `[16-way-compass]` will translate to "N", "NE", "NNE" respectively, along the same lines as existing generation (direction from surface center).
- `[distance]` will translate to the distance from center, as existing generation.
- `[center-xy]` will translate to coordinates of the site center, e.g., "123,-124".
- `[index]` will translate to an automatically-assigned index that uniquely identifies the site -- this will also be the actual index of the site inside its storage. NB: Indexes are per-force, if you have two forces they can each have a site 1, 2, etc..
- `[ore-icon]` will translate to the icon(s) of the resource's mining result, as in the already existing column. In vanilla, this would be `[item=copper-ore]`, etc..
- `[ore-name]` will translate to the name of the resource entity, as in the already existing column.
    - NB: if someone makes an ore with multiple outputs, e.g., **galena** which can bear *lead* and *silver*, the ore icons would be *lead* and *silver* ore items, but the ore name would still be **galena**. This is the existing behaviour for the relevant columns and is being reused here.

Finally, every site can have a "name tag", which is configured by the player using the rename icon and will always be displayed:
- if the tag `[name-tag]` is specified in the auto-naming configuration, it will be placed there
- otherwise, it will be added after the auto-generated name

**Comment by narc0tiq** [comment]
One further note: to keep things simple for myself, any text outside of `[tags]` from the setting will be ignored altogether -- I can think of some ways to potentially collect extra punctuation, literals, etc., but it would take extra time and there is an increased risk of bugs. If there is interest, I will consider introducing this capability but not for the 1.0 release.

Instead, what I will do is make a `[f-<anything>]` tag through which you can introduce a fixed text. For example, `[f-const]` will introduce the text `const` in that position.
NB: The text will be introduced without any whitespace, so `[planet] [f-const] [4-way-compass]` will result in `NauvisconstE` -- you should use `[f- const ]` if you want `Nauvis const E`.

**Comment by narc0tiq** [comment]
So I just figured out that with the `[f-blah]` support, I could just generate fixed texts:
- everything from the start of the string to the first [,
- everything between ] and [,
- everything after the last ]

It occurs to me that using {curly braces} would be better if you, the player, wanted to include some [entity=electric-miner] in your fixed text. But do you really?
It also occurs to me that I have no idea what happens if you put [brackets [in brackets] like this]. Probably nothing good.

**Comment by narc0tiq** [comment]
Here we go, 1.0 hype:
![image](https://github.com/user-attachments/assets/7f8b4da8-1cba-4f72-9cc0-d17dc9a512ce)
