### ISSUE TITLE
Add brief summary of what this mod does to the readme

### ISSUE THREAD

**Issue by djmattyg007** [narc0tiq/YARM#49]
It took me quite a while to realise that I had to research some tech and craft items in order to use this mod.

**Comment by narc0tiq** [comment]
Agreed, I need to write a short how-to. Sticking it in the readme makes perfect sense. Thanks for the reminder!

**Comment by narc0tiq** [comment]
Check out https://github.com/narc0tiq/YARM#how for a summary -- it maybe could do with a picture or two, but this should work for for the moment.
