### ISSUE TITLE
Web integration

### ISSUE THREAD

**Issue by magnus97** [narc0tiq/YARM#50]
Is it possible to get a web integration to list all of the stats and see what has bean used in this amount of time from the ores you have scanned?

**Comment by narc0tiq** [comment]
Uh, I think I understand what you're asking -- generate some HTML in the `script-output` that could be used to watch YARM status (and collected statistics) from a browser; please correct me if I misunderstood -- but it seems awfully far out of scope for a Factorio mod.

Nonetheless, I like the idea and will keep it in mind -- it sounds like fun!

**Comment by mexmer** [comment]
i would suggest outputing simple formated text (like csv/json), and let all people convert it to whatever they want.

@narc0tiq i agree with you, that generating full fledged html is out of mod scope, but saving current stats in configurable interval, doesn't seem too far fetched.

**Comment by narc0tiq** [comment]
@mexmer Sounds good to me; it shouldn't be too tricky to then set up a static HTML piece with some javascript to automatically reload the data straight out of the JSON or CSV (probably the former), assuming it's published.

I really like this idea and will look into making it a reality for 0.8.

**Comment by narc0tiq** [comment]
I'm going to drop this feature; for an alternative, take a look at [graftorio](https://mods.factorio.com/mod/graftorio), which can read from YARM, and provides data to a [Grafana](https://grafana.com/) dashboard.
