### ISSUE TITLE
Remote viewer: allow multiple views per tracked site

### ISSUE THREAD

**Issue by Thel89** [narc0tiq/YARM#54]
As touched on in https://github.com/narc0tiq/YARM/pull/53 - if we're to allow geographically disparate patches to be tracked together, that reduces the usefulness of remote viewing. (The remote view puts the view box in middle of the extents of the overall site. That means if you have a site of multiple patches, separated by some distance vertically, the viewer will be looking at the empty space in middle of your tracked site.)

Suggested improvement: allow multiple views per tracked site, one per patch.

Suggested approach:
- each time you smack the YARM on a resource, note that location in the site data (unless the resource is already tracked in the current site) - @narc0tiq did mention about [potentially leaving an entity in the game world](https://github.com/narc0tiq/YARM/pull/53#issuecomment-260306171), but I'm not sure if that's necessary (or what we'd gain from it)
- then change the remote view UI to have back and forward buttons
- and code to support the multiple views

Tangentially related: https://github.com/narc0tiq/YARM/issues/10 (ability to review site overlay - we'll get that basically for free once the site merging code goes in. However with geographically distant sites, the site overlay is largely useless for the same reasons remote view is useless)

**Comment by narc0tiq** [comment]
> (unless the resource is already tracked in the current site)

We could potentially just allow that; I wouldn't mind being able to have multiple views of a large contiguous patch.


> potentially leaving an entity in the game world, but I'm not sure if that's necessary (or what we'd gain from it)

It looks good (potentially), and it can be something to attach the player to (instead of spawning an invisible player character-like entity). It could even consume some resources, though I don't imagine that change would be very popular.


> back and forward buttons

Or just one "next camera" button to complement the "stop viewing" one.

**Comment by narc0tiq** [comment]
Fixed by v0.8 in as much as your vision depends on radar coverage now. Scroll as needed.
