### ISSUE TITLE
Remove the item requirement

### ISSUE THREAD

**Issue by narc0tiq** [narc0tiq/YARM#55]
Via <https://github.com/narc0tiq/YARM/pull/53#issuecomment-261525265>:

> > I guess the other option there would be to bring the player's YARM into their cursor (assuming they have a YARM and their cursor is empty).
>
> Yes, I hadn't considered it, but that's a fair point and I rather like it.
>
> On that note, an "add site" button could do the same just for general adding. And then, you know, we could just remove the recipe for the resource monitor item and just spawn one when the player needs it (and discard it thereafter). And I've just talked myself into a largish UX change that I'm going to go ahead and shove into a different issue.

Important point, if the player already has something in their cursor, we need to consider it. Options are:
- just error out,
- attempt to drop it into their inventory (erroring if it fails),
- drop it into their inventory or else on the ground (erroring if *that* fails), or
- put the item into hammerspace (i.e., just remember what it was) and restore it later.

On a related note, consider removing the technology requirement, as well.

**Comment by Thel89** [comment]
Another option, rather than having an item and smacking it on the ground - have a generic add-site button, and kick a search off from where the player is standing.

**Comment by narc0tiq** [comment]
Right, but that comes with its own trade-offs: the player has to stand on or near an oil spout, and that's a little more awkward -- and making it a larger search area makes it harder to select what you want out of a mixed ore field. Mouse precision is definitely greater than player position precision, especially when you get up into the large numbers of power armor legs.

Mitigation: show the player a list of the kinds of ores there are nearby (if there are multiple) and let them choose which they want to start tracking. That makes things viable, but I'm not sure if it's better than just keeping the existing process.

**Comment by Nexela** [comment]
If you use a hot-key combination
You can use player.selected to get the position of the selected entity

however I like using the remote it brings a little bit of immersion as the player has to do something 

> Important point, if the player already has something in their cursor, we need to consider it. Options are:
Take a look at the Picker or Picker Extended mods for examples on how it is handled there.

**Comment by narc0tiq** [comment]
Fixed by v0.8, which uses Factorio 0.17's new shortcut bar (and also a hotkey).
