### ISSUE TITLE
Optional map markers for ore sites

### ISSUE THREAD

**Issue by narc0tiq** [narc0tiq/YARM#6]
Automatically create/update map markers (Factorio calls them 'chart tags') for the ore deposits they live in:

- [x] Create a new tag at site center when a site is created
- [x] Update the tag when the site is renamed
- [x] Update when the site is extended
- [x] Delete when the site is deleted
- [x] ~~Rename site when chart tag is renamed~~

Optional:
- [x] Include some stats (e.g., "90% of 10M = 9M") in the chart tag, updating it when the site is recounted; one of:
    - short: `CURRENT_SIZE` e.g., `9M`
    - ~~medium: `CURRENT_SIZE/CURRENT_PERCENT`, e.g., `9M/90%`~~
    - ~~long: `CURRENT_PERCENT of ORIGINAL_SIZE = CURRENT_SIZE`, e.g., `90% of 10M = 9M`~~
- [x] ~~Perhaps a config option to switch between the three possibilities?~~
- [x] Carefully handle renaming from chart tag:
    - either disallow, or 
    - ~~try to strip the stats from the new name before applying it (assume stats are in parentheses, therefore strip parentheses from the chart tag to obtain the intended new name).~~

Original description below:

---

The player should have a way to place map markers ~~(based on train stops)~~ on ore sites they're particularly interested in. These should be optional, invisible to biters, and removed when the site is removed.

~~Note: because these would be based on train stops, they can pollute the train scheduling interface; ideally, we should avoid this feature until it's possible to create map markers that aren't train stops.~~

Alternate implementation: we could provide a way to link sites to actual train stops, e.g., by clicking a UI button and then tapping the train stop with the resource monitor tool, renaming the train stop with the site name. In this case, multiple train stops should be able to be linked to the same ore site. Additionally:
- when the site is depleted, we should update the train stop name with a prefix indicating this;
- when the site is deleted (read carefully now), we should either return the train stop's original name, or just apply another prefix;
- the above should be optional behaviours controlled by the YARM settings

**Comment by dgw** [comment]
In 0.15, there is support for map markers on the map, text and an icon to mark the spot. That seems pretty perfect for this issue. Except…

The Lua API documentation has [a class for it](http://lua-api.factorio.com/0.15.21/LuaCustomChartTag.html), but I haven't found any methods for creating a tag—only for destroying an existing one.

**Comment by narc0tiq** [comment]
> haven't found any methods for creating a tag

http://lua-api.factorio.com/latest/LuaForce.html#LuaForce.add_chart_tag

**Comment by dgw** [comment]
That's definitely not where I expected to find anything map-related… but I'm no modder. I haven't even had the game a month!

**Comment by narc0tiq** [comment]
Yeah, I had to trawl the docs for a good half-hour or more before finally noticing it. Luckily, it looks okay to use.
