### ISSUE TITLE
Re: the Fake player

### ISSUE THREAD

**Issue by Nexela** [narc0tiq/YARM#61]
The new Factorio doesn't allow entity health to be set to 0 when talking about a player-type, so we're setting destructible = false instead. Same effective behaviour, just a different way to achieve it.

Could remove the player all together and use a Camera GUI

**Comment by narc0tiq** [comment]
Yes, that would be vastly preferable. Those were just porting notes to remind me what I did to get it working.

**Comment by narc0tiq** [comment]
Finally removed the fake player in v0.8.
