### ISSUE TITLE
Can't find monitor

### ISSUE THREAD

**Issue by jeron-diovis** [narc0tiq/YARM#62]
Probably it's a quite dumb question, but... where this monitor should be in crafting menu?
I researched the technology, and now just can't find it's icon to craft one.

<img width="1384" alt="screenshot 2017-06-06 23 59 09" src="https://user-images.githubusercontent.com/2756868/26851428-7d715dc6-4b13-11e7-8f4e-2c0dc4c986f8.png">

It's neither among combinators and logistic:
<img width="431" alt="screenshot 2017-06-06 23 55 44" src="https://user-images.githubusercontent.com/2756868/26851280-0e6aa2a2-4b13-11e7-9669-977f24b09e08.png">

nor among factories:
<img width="425" alt="screenshot 2017-06-06 23 55 54" src="https://user-images.githubusercontent.com/2756868/26851279-0e64f5e6-4b13-11e7-8298-78b284b5997d.png">

and, actually, nowhere else.

Playing Factorio 0.15.18, with Bob's mod installed.

**Comment by narc0tiq** [comment]
I assume you've tried the search function, since you know the recipe name (Монитор ресурсов) from its listing on the technology page. Normally, it should be on the production tab, right next to the repair packs, as in [this image](https://i.imgur.com/nRt6CIi.png), but apparently something's messing with it. But it ain't YARM, so it must be another of your current set of mods.

**Comment by QCU87Z** [comment]
I have the same issue I have completed the research

**Comment by narc0tiq** [comment]
I still don't have a mod list, and it still works for me. I can't really help you without more information.

**Comment by jeron-diovis** [comment]
@narc0tiq do you mean that another mod could add item with the same name as YARM does?
I tried search, of course, both with english and russian versions, but nothing found. 

Also tried trick with turning mod off, saving, and turning it back on – so research becomes incompleted, and I can perform it again. But this didn't help.

Here is the full list of what I have installed, if it can be useful:
[mod-list.json.zip](https://github.com/narc0tiq/YARM/files/1058529/mod-list.json.zip)

**Comment by QCU87Z** [comment]
That is my mod list the only thing I will add is that the mod was added on a world that was already existing.

`{
  "mods": [
    {
      "name": "base",
      "enabled": true
    },
    {
      "name": "alien-biomes",
      "enabled": true
    },
    {
      "name": "angelsinfiniteores",
      "enabled": true
    },
    {
      "name": "angelspetrochem",
      "enabled": false
    },
    {
      "name": "angelsrefining",
      "enabled": true
    },
    {
      "name": "angelssmelting",
      "enabled": true
    },
    {
      "name": "AutoDeconstruct",
      "enabled": true
    },
    {
      "name": "AutoTrash",
      "enabled": true
    },
    {
      "name": "bobassembly",
      "enabled": false
    },
    {
      "name": "bobelectronics",
      "enabled": false
    },
    {
      "name": "bobenemies",
      "enabled": false
    },
    {
      "name": "bobgreenhouse",
      "enabled": false
    },
    {
      "name": "bobinserters",
      "enabled": true
    },
    {
      "name": "boblibrary",
      "enabled": false
    },
    {
      "name": "boblogistics",
      "enabled": true
    },
    {
      "name": "bobmining",
      "enabled": false
    },
    {
      "name": "bobmods_gfxtweak",
      "enabled": true
    },
    {
      "name": "bobmodules",
      "enabled": true
    },
    {
      "name": "bobores",
      "enabled": true
    },
    {
      "name": "bobplates",
      "enabled": true
    },
    {
      "name": "bobpower",
      "enabled": true
    },
    {
      "name": "bobrevamp",
      "enabled": true
    },
    {
      "name": "bobtech",
      "enabled": true
    },
    {
      "name": "bobvehicleequipment",
      "enabled": true
    },
    {
      "name": "bobwarfare",
      "enabled": true
    },
    {
      "name": "Bottleneck",
      "enabled": true
    },
    {
      "name": "BottleneckLogistics",
      "enabled": true
    },
    {
      "name": "bullet-trails",
      "enabled": true
    },
    {
      "name": "BurnerLeech",
      "enabled": true
    },
    {
      "name": "crafting_combinator",
      "enabled": true
    },
    {
      "name": "Crafting_Speed_Research",
      "enabled": true
    },
    {
      "name": "data-raw-prototypes",
      "enabled": true
    },
    {
      "name": "even-distribution",
      "enabled": true
    },
    {
      "name": "Expanded_Robot_Tech",
      "enabled": true
    },
    {
      "name": "Factorissimo2",
      "enabled": true
    },
    {
      "name": "FARL",
      "enabled": true
    },
    {
      "name": "GDIW",
      "enabled": true
    },
    {
      "name": "GDIWHotkey",
      "enabled": true
    },
    {
      "name": "helmod",
      "enabled": true
    },
    {
      "name": "Laser_Beam_Turrets",
      "enabled": true
    },
    {
      "name": "Loader-Rotation-Fix",
      "enabled": false
    },
    {
      "name": "LoaderRedux",
      "enabled": true
    },
    {
      "name": "longer-belts-redux",
      "enabled": true
    },
    {
      "name": "Nanobots",
      "enabled": true
    },
    {
      "name": "PickerExtended",
      "enabled": true
    },
    {
      "name": "research-queue",
      "enabled": true
    },
    {
      "name": "rso-mod",
      "enabled": true
    },
    {
      "name": "SmarterBotRecharge",
      "enabled": true
    },
    {
      "name": "Squeak Through",
      "enabled": true
    },
    {
      "name": "StickyNotes",
      "enabled": true
    },
    {
      "name": "textplates",
      "enabled": true
    },
    {
      "name": "upgrade-planner",
      "enabled": true
    },
    {
      "name": "VehicleSnap",
      "enabled": true
    },
    {
      "name": "Warehousing",
      "enabled": true
    },
    {
      "name": "water-fix",
      "enabled": true
    },
    {
      "name": "what-is-it-really-used-for",
      "enabled": true
    },
    {
      "name": "what_is_it_used_for_15",
      "enabled": false
    },
    {
      "name": "YARM",
      "enabled": true
    }
  ]
}
`

**Comment by QCU87Z** [comment]
Also it works fine once I cheated the item in with console commands

**Comment by narc0tiq** [comment]
Good news: with an intersection of your two mod sets, I'm seeing the same behaviour. It looks like Picker Extended is taking over and just providing the monitor on demand (press Shift+B to open the full list of what's available, or Ctrl+Q to scroll through available planners).

[It's listed on the mod description page](https://mods.factorio.com/mods/Nexela/PickerExtended) -- Ctrl+F `Picker additional Planners`.
