### ISSUE TITLE
Remote viewer unceremoniously boots the player from their vehicle

### ISSUE THREAD

**Issue by dgw** [narc0tiq/YARM#66]
I was hurrying off in a train to the next job while renaming the last ore site I added, and found upon returning to the normal view (since renaming sites requires entering the remote viewer) that I'd been booted out of my train.

The Fat Controller handles this well: If you try to remote-control a train while in another vehicle, it prints a message to the console, informing the player that they must exit their current vehicle to do that, and does not change the view. That's vastly preferable to being kicked out of a (perhaps high speed) train without warning.

**Comment by narc0tiq** [comment]
Interesting. What I recall from the last time I tried this is that the character I switched out of would remain in the vehicle it was in, but this is clearly no longer the case. I wonder when that changed.

Regardless, I do need to fix it. Thanks for bringing it up!

**Comment by dgw** [comment]
Hmm… I did a little digging in the code, found how YARM is replacing the player character with the remote viewer, and ran a quick search on the Factorio forums. Another mod had this kind of issue, but sadly, the response from Rseding91 is that it's "working as intended":

> Switching the character entity switches the controller the player is using and when that happens it ejects the player from any vehicle they're in to make sure the state remains correct on the character entity, the vehicle, and the player.
>
> In 0.14 and previous it would leave the character in an invalid state.

— https://forums.factorio.com/viewtopic.php?f=7&t=47874#p276358

**Comment by narc0tiq** [comment]
Thanks for researching! I ended up just preventing character change altogether while in a vehicle, which made the most sense given what Rseding91 said. Basically the The Fat Controller solution.
