### ISSUE TITLE
YARM silently overwrites existing site if new one has the same automatic name

### ISSUE THREAD

**Issue by dgw** [narc0tiq/YARM#68]
I went around adding several uranium patches to YARM after setting up the mines, trains, etc. I got very confused when after adding four sites, only two appeared in YARM's list.

Long story short, I had to go back, re-add the missing sites, and rename them as I went because three of the four were getting the same automatically generated name (`NW 1253` or similar, due to relative proximity I guess).

It strikes me as odd that YARM silently overwrites existing sites in this manner. The failure mode I expected to find was that YARM had combined them, but that was not the case.

IMO the ideal outcome would be to append "A", "B", etc. to the site name if it conflicts with an entry in the list. But feel free to tell me "Just rename each site as you create them, noob!" :) Though that would be easier if doing so did not require remote viewing the site first. (At least I was not kicked out of my train again, thanks to your fix the other day.)

**Comment by narc0tiq** [comment]
Yes, this is a problem. It's also reported as #52, so we'll keep that one.

**Comment by dgw** [comment]
Ach, how did I miss that one? My most profuse apologies for the duplicate report!
