### ISSUE TITLE
Recipe exists in game, but is not craftable

### ISSUE THREAD

**Issue by jbo18** [narc0tiq/YARM#73]
I installed the mod and researched the tech, but the recipe does not show up in the crafting menu.  However, the recipe is visible in the tech screen and in the "what is it really used for?" mod.  Are there any mods that are known to conflict or cause issues with the monitor?
Modlist: https://pastebin.com/WFwHEaes

**Comment by narc0tiq** [comment]
It's a Picker Extended feature -- the monitor is in your planners. See also <https://github.com/narc0tiq/YARM/issues/62#issuecomment-307054154>.
