### ISSUE TITLE
Hot keys to take you out of view mode

### ISSUE THREAD

**Issue by ChuckSavage** [narc0tiq/YARM#76]
I find myself trying to use WASD all the time when using the view mode. An option when movement keys (and/or) the escape key are used, should take you out of view mode.

**Comment by rgant** [comment]
Agreed, I'm always clicking `e` to try and close the view mode like you can close the default dialogs in the game.

**Comment by narc0tiq** [comment]
Fixed by v0.8, which removes the hacky remote view by fake player character. Now remote viewing just relies on the map/zoom to world.
