### ISSUE TITLE
Show a summary of known ore sites (e.g., by ore type)

### ISSUE THREAD

**Issue by narc0tiq** [narc0tiq/YARM#8]
By request from KeyboardHack on the IRC, it would be nice to have a way to put the YARM site list into a summary mode, where all ore sites of the same ore type are added together and you see a total of your stats for each ore type.

**Comment by georgehank** [comment]
Seconded.  I was hunting for such a mod when I started a high scarcity play: all resources low frequency, very small fields, very low richness.

Although I'd like there to be a way to auto-add detected sites for this play, but... that's another issue.

**Comment by narc0tiq** [comment]
Resolved in v0.9.1 (2023-05-31)
