### ISSUE TITLE
Renaming site while after exiting remote view breaks the UI

### ISSUE THREAD

**Issue by efalder413** [narc0tiq/YARM#82]
Steps to reproduce:

1. Set up a site as normal
2. Open remote view
3. Open the rename dialog
4. Close remote view
5. Hit "Do It!"

The site will then still have the buttons as if you were in remote view, locking you out of viewing that site. YARM will ask you to call reset_player if you try to exit again, but saving/loading also appears to fix it (and doesn't stop achievments).

**Comment by narc0tiq** [comment]
Huh, that's a sequence I didn't think of. Thanks for the report, I'll need to consider the solution (probably cancel the rename if you stop viewing).

Also, I think you can view a different site to fix it; at the very least, give that a try and let me know if it doesn't work.

**Comment by efalder413** [comment]
Yes, that does also fix it.

**Comment by narc0tiq** [comment]
Fixed in v0.8 by the removal of the remote viewer fake player -- remote view now simply opens the map to the right place.
