### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Equitime77** [narc0tiq/YARM#97]
Im using the 0.17.24. I have been able to get some sites linked with yarm, but something happened and for the past few updates its not working at all. I cannot add any new sites.

**Comment by narc0tiq** [comment]
Hi, @Equitime77, thanks for the interest!

It might be that you're used to the old way of marking ores, with a single click (exactly one ore at a time). The new tool, that doesn't require a crafted item nor a research, is used more like the blueprint tool: drag-select a region containing one or more of the target ores. YARM will still expand the search as much as possible thereafter, as it always has.

I've updated the readme and there is also now a change log that will allow reviewing changes in behavior when they occur. I hope this will help reduce future confusion, and allow you to continue enjoying YARM.

Please reopen this issue if it's still not working for you; if that happens, I'd also appreciate a copy of the save where this occurs, so I can check for mod interactions.
